language: python
deploy:
  provider: npm
  api_token: 
     secure: "FunO9W4xOhBPdph6EaWb4BukNE0Xsfm/4eDPxNl9VhrDVH3prqhuQN3eRte1+ucb9RHsPlWXO3Xnuj+CQl3S5x0k84tP/Df9/OTSXoRMvXVmhCRpwVR5AK5fIKnzQSjRh0CaRWcLNj718/AGMYtBLnF8miO2Fv03z4PdJjB24EgACONhZOy8eTJ3WYU0FEZWvTb+/yRY8S5vKPw/e6o28CjQT0WsWjWoNOm3tJJInd7w0885BcDH9At7ca8T+EvPKEtcdBvoaCD6kxr0JjAgHC8JFpIR82IGfsotlDhxv1L/MDLaTXlciWihzx7zMHDESDz9GHeDo7HmxycL65yC4yRcQsmZiT7TgHLJ3BF903hXil6OE4Y9PYok9Mh+uLeO8r7eogFZvMi/zEqpxpAPXOlpaSLDXShBdw0YaUCuZXhZHigk+ybEChSH9OK+t/qDBKLdX9smWodbvx9XKZc9VnxcK3LffZfzDO9rwQEe8LD3ezEXPebsyxHT9HC9+W0EhgBthwx5V/N7WcKr3N3RQGwHPBsVDJ0QYIffcG5thWZtYamqeOKhhIU1w1kqK/tf4MiPGrqJL5pM0f865wxFBxN2bUNu+muA28ivJFueHtBQLLt0BWnS7AJg+RU6VQbQSNNVuhZMv7XkdAzeLkoeZF4QcjgJ32wae6/C57gvMTs="
  email: arthana.h@celestialsys.com
  access: public
  edge: true
  on:
   branch:
     - main
script: 
  - python hello_world.py
